name: Draai CHO-diff pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  ceo-diff:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download TriplyDB CLI
        run: |
          Invoke-WebRequest -Uri https://static.triply.cc/cli/triplydb.exe -OutFile triplydb.exe

      - name: Haal datums op
        id: datums
        shell: pwsh
        run: |
          $vandaag = Get-Date -Format "yyyy-MM-dd"
          $gisteren = (Get-Date).AddDays(-1).ToString("yyyy-MM-dd")
          echo "vandaag=$vandaag" >> $env:GITHUB_OUTPUT
          echo "gisteren=$gisteren" >> $env:GITHUB_OUTPUT

      - name: Login en voer SPARQL-query uit
        run: |
          .\triplydb.exe login --token "${{ secrets.TRIPLYDB_TOKEN }}" --url https://api.linkeddata.cultureelerfgoed.nl
          .\triplydb.exe query rce/cho query.rq --format turtle > output.ttl

      - name: Upload resultaat naar nieuwe dataset
        run: |
          $vandaag = "${{ steps.datums.outputs.vandaag }}"
          .\triplydb.exe dataset create rce ceo-$vandaag --visibility private || exit 0
          .\triplydb.exe dataset import rce/ceo-$vandaag output.ttl --format turtle

      - name: Bereken verschil met gisteren en sla op
        run: |
          $vandaag = "${{ steps.datums.outputs.vandaag }}"
          $gisteren = "${{ steps.datums.outputs.gisteren }}"

          .\triplydb.exe diff rce/ceo-$gisteren rce/ceo-$vandaag > diff.ttl || echo "Geen verschil"
          .\triplydb.exe dataset create rce ceo-diff-$vandaag --visibility private || exit 0
          .\triplydb.exe dataset import rce/ceo-diff-$vandaag diff.ttl --format turtle || echo "Geen diff"

      - name: Synchroniseer Triply services
        shell: pwsh
        run: |
          $headers = @{
            "Authorization" = "Bearer ${{ secrets.TRIPLYDB_TOKEN }}"
            "Content-Type"  = "application/json"
          }

          $body = '{ "sync": true }'

          $services = @("ceo-diff-latest", "ceo-diff-view")
          foreach ($service in $services) {
            $url = "https://api.linkeddata.cultureelerfgoed.nl/datasets/rce/ceo-diff-${{ steps.datums.outputs.vandaag }}/services/$service"
            Write-Host "Synchroniseer service: $service"
            Invoke-RestMethod -Uri $url -Method POST -Headers $headers -Body $body
          }
