name: CHO-diff per dag

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  cho-diff:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download TriplyDB CLI (triplydb.exe)
        run: |
          Invoke-WebRequest -Uri https://static.triply.cc/cli/triplydb.exe -OutFile triplydb.exe

      - name: Haal datum op
        id: datum
        shell: pwsh
        run: |
          $vandaag = Get-Date -Format "yyyy-MM-dd"
          echo "vandaag=$vandaag" >> $env:GITHUB_OUTPUT

      - name: Download RDF-resultaat van Triply API-query
        run: |
          curl -X POST -H "Accept: text/turtle" "https://api.linkeddata.cultureelerfgoed.nl/queries/rce/Query-11-4/2/run?page=1&pageSize=200" -o diff.ttl

      - name: Zet diff.ttl om naar correct diff.trig met named graph
        shell: pwsh
        run: |
          $datum = "${{ steps.datum.outputs.vandaag }}"
          $prefixes = @()
          $triples = @()
          $inTriples = $false

          foreach ($line in Get-Content diff.ttl) {
            if ($inTriples) {
              $triples += $line
            }
            elseif ($line -match "^\s*$") {
              $inTriples = $true
            }
            else {
              $prefixes += $line
            }
          }

          $graphUri = "<https://linkeddata.cultureelerfgoed.nl/graph/cho-diff/$datum>"
          $output = $prefixes + "" + "$graphUri {" + $triples + "}"
          $output | Set-Content diff.trig -Encoding UTF8

      - name: Upload diff.trig naar rce/cho via import-from-file
        run: |
          .\triplydb.exe import-from-file `
            --account rce `
            --dataset cho `
            --token "${{ secrets.TRIPLYDB_TOKEN }}" `
            --url https://api.linkeddata.cultureelerfgoed.nl `
            diff.trig
