name: Draai CHO-diff vanuit vaste API-query

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  cho-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installeer TriplyDB CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g @triply/triplydb-cli

      - name: Haal datum op
        id: datum
        run: echo "vandaag=$(date +%F)" >> $GITHUB_OUTPUT

      - name: Haal RDF-resultaat van Triply API-query op
        run: |
          curl -X POST \
            -H "Accept: text/turtle" \
            https://api.linkeddata.cultureelerfgoed.nl/queries/rce/Query-11-4/1/run \
            -o diff.ttl

      - name: Zet diff.ttl om naar diff.trig met named graph
        run: |
          datum="${{ steps.datum.outputs.vandaag }}"
          echo "<https://linkeddata.cultureelerfgoed.nl/graph/cho-diff/$datum> {" > diff.trig
          cat diff.ttl >> diff.trig
          echo "}" >> diff.trig

      - name: Upload diff.trig naar bestaande dataset rce/cho
        run: |
          triplydb dataset import rce/cho diff.trig --format trig \
          --token "${{ secrets.TRIPLYDB_TOKEN }}" \
          --url https://api.linkeddata.cultureelerfgoed.nl
