name: Draai CHO-diff naar één dataset (Linux + volwaardige CLI)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  cho-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installeer Node.js en TriplyDB CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g @triply/triplydb-cli

      - name: Haal datums op
        id: datums
        run: |
          echo "vandaag=$(date +%F)" >> $GITHUB_OUTPUT

      - name: Draai SPARQL-query op rce/cho
        run: |
          triplydb query rce/cho query.rq --format turtle > diff.ttl \
          --token "${{ secrets.TRIPLYDB_TOKEN }}" \
          --url https://api.linkeddata.cultureelerfgoed.nl

      - name: Zet diff.ttl om naar diff.trig met named graph
        run: |
          datum="${{ steps.datums.outputs.vandaag }}"
          echo "<https://linkeddata.cultureelerfgoed.nl/graph/cho-diff/$datum> {" > diff.trig
          cat diff.ttl >> diff.trig
          echo "}" >> diff.trig

      - name: Upload diff.trig naar rce/cho
        run: |
          triplydb dataset import rce/cho diff.trig --format trig \
          --token "${{ secrets.TRIPLYDB_TOKEN }}" \
          --url https://api.linkeddata.cultureelerfgoed.nl
